---
services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10-dind
    alias: docker

before_script:
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

stages:
  - test

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

test4.4:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:4.4
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test

test5.0:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:5.0
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test

test5.1:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:5.1
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test

test5.2:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:5.2
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test
