---
services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10-dind
    alias: docker

before_script:
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

stages:
  - test

test4.4:
  stage: test
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hbl-testing-image:4.4
  before_script:
    - npm ci
    - ls -al
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test
