---
stages:
  - test

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

test4.4:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:4.4
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test

test5.0:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:5.0
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test

test5.1:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:5.1
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test

test5.2:
  stage: test
  image:
    name: gitlab-registry.dubzland.net/holodekk/hbl-testing-image:5.2
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="$PWD/node_modules" npm test
