---
stages:
  - test

test:
  stage: test
  cache:
    key: npm
    policy: pull-push
    paths:
      - .npm/
  parallel:
    matrix:
      - BASH_VERSION: ['4.4', '5.0', '5.1', '5.2']
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/bash:${BASH_VERSION}
  before_script:
    - apk add --update-cache npm
    - npm ci --cache .npm --prefer-offline
  script:
    - BATS_LIB_PATH="${PWD}/node_modules" npm test
